---
- name: Install yum packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - php
  - mod_php
  - mod_python
  - mod_wsgi
  - php-mysql
  - python-imaging
  - python-pip
  - mariadb

- name: Install pip packages
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_dict:
  - name: Django
    version: 1.3.1
  - name: django-storages
    version: 1.4.1
  - name: awscli
    version: 1.10.28

- name: Add config include to http.conf
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    line: "IncludeOptional \"/srv/*/etc/*.conf\""
